name: Update Dependencies
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10 * * 1'
jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up python
        uses: action/setup-python@v1
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with: 
          version: 1.1.4
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs
      - name: Cache poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}          
      - name: Update dependencies
        run: |
          poetry update
      - name: Create Pull request
        uses: peter-evans/create-pull-request@7b1819c0925468602327a69656b53a2702b9ef0b
        with:
          base: master
          token: ${{ secrets.PAT }}
          commit-message: Updated Dependencies
          title: Update dependencies
          body: |
            - Deps updated

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
          
        
          
