# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 1
      - name: Set up Python 
        uses: actions/setup-python@v1
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with: 
          version: 1.1.4
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs
      - name: Cache poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}          
      - name: Install Deps
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      
      - name: Code Quality
        run: poetry run black . --check
      - name: Test with pytest
        run: poetry run pytest --cov=das_builder 
